# This is a basic workflow to help you get started with Actions

name: Download Comic
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: '安装依赖'
        run: |
          pip install pillow requests fake_useragent bs4 PyPDF2 lxml
          
      - name: '下载漫画'
        run: |
          python main.py
          
      - name: '压缩文件'
        run: |
          tar -cvpzf uncombine.tgz ./uncombine
          tar -xvpzf results.tgz ./results
          
#       - uses: actions/upload-artifact@v3
#         name: '上传文件'
#         with:
#           name: manga
#           path: /home/runner/work/Comic_Spider/Comic_Spider/output.tgz
      - name: Release
        uses: softprops/action-gh-release@v1
          
        with:
          tag_name: Temp
          token: ${{ secrets.TOKEN }}
          name: manga
          body: Download
          draft: false
          prerelease: false
          files: |
            /home/runner/work/Comic_Spider/Comic_Spider/uncombine.tgz
            /home/runner/work/Comic_Spider/Comic_Spider/results.tgz
